# Assignment Brief de UNIT 19 - DATA STRUCTURES & ALGORITHMS

**Autor: Rubén Valverde Romero**

### Análisis de Riesgo

Al realizar este trabajo sobre algoritmos de camino más corto, podría encontrarme con varios problemas que dificulten el desarrollo del proyecto: 

1. **Incompatibilidad de Librerías**: Podría suceder que las versiones de las librerías utilizadas (como `networkx`, `numpy`, `scipy`, etc.) no sean compatibles entre sí, lo que generaría errores difíciles de depurar. Sería crucial asegurarme de que todas las librerías estén actualizadas y sean compatibles.

2. **Complejidad Computacional**: Al trabajar con grafos grandes, los algoritmos de camino más corto pueden volverse extremadamente lentos y consumir una gran cantidad de memoria. Debería optimizar mi código y considerar el uso de estructuras de datos eficientes para manejar grafos de gran tamaño, aun así existe el riesgo de que mi pc se congele.

3. **Conversión a PDF**: Pasar un notebook a PDF puede ser tedioso y problemático, especialmente si contiene gráficos y visualizaciones complejas. Debería asegurarme de que todas las celdas se rendericen correctamente y de que el formato final sea legible y profesional.

### Justificación Técnica de Herramientas y Lenguajes

En este proyecto se han utilizado diversas herramientas y lenguajes de programación para abordar el problema de encontrar caminos más cortos en grafos. A continuación, se presenta una justificación técnica de las herramientas y lenguajes empleados:

1. **Python**:
    - **Bibliotecas Especializadas**: Python cuenta con una amplia gama de bibliotecas especializadas para el análisis y manipulación de grafos, como `networkx`, `numpy`, `scipy`, y `matplotlib`, que simplifican el desarrollo y la visualización de soluciones.

2. **NetworkX**:
    - **Manipulación de Grafos**: `networkx` es una biblioteca de Python diseñada para la creación, manipulación y estudio de la estructura, dinámica y funciones de grafos complejos. Permite una fácil implementación y análisis de grafos.
    - **Algoritmos Integrados**: Proporciona una variedad de algoritmos integrados para el análisis de grafos, incluyendo algoritmos de caminos más cortos, lo que facilita la implementación y comparación de diferentes métodos.

3. **NumPy**:
    - **Eficiencia Computacional**: `numpy` es una biblioteca fundamental para la computación científica en Python. Proporciona soporte para arrays y matrices multidimensionales, junto con una colección de funciones matemáticas de alto nivel para operar con estos arrays.
    - **Manejo de Datos**: Facilita el manejo y la manipulación eficiente de grandes conjuntos de datos, lo cual es crucial para el análisis de grafos y la implementación de algoritmos de caminos más cortos.

4. **SciPy**:
    - **Algoritmos Avanzados**: `scipy` es una biblioteca de Python utilizada para la computación científica y técnica. Incluye módulos para la optimización, álgebra lineal, integración, interpolación, funciones especiales, y más.
    - **Algoritmos de Grafos**: Proporciona implementaciones eficientes de algoritmos de caminos más cortos, como Dijkstra, Bellman-Ford, Johnson y Floyd-Warshall, lo que permite comparar el rendimiento y la eficiencia de diferentes métodos.
5. **Matplotlib**:
    - **Visualización de Grafos**: `matplotlib` es una biblioteca de Python utilizada para crear visualizaciones estáticas, animadas e interactivas. Se ha utilizado para visualizar los grafos y sus propiedades de manera clara y comprensible.
    - **Flexibilidad y Personalización**: Permite una gran flexibilidad y personalización en la creación de gráficos, lo que facilita la representación visual de los resultados del análisis de grafos.

6. **Visual Studio Code**:
    - **Entorno de Desarrollo Integrado (IDE)**: Visual Studio Code es un editor de código fuente desarrollado por Microsoft. Ofrece soporte para la depuración, control de versiones, y una amplia gama de extensiones que mejoran la productividad.
    - **Facilidad de Uso**: Su interfaz intuitiva y personalizable facilita el desarrollo y la gestión de proyectos de programación, incluyendo aquellos que involucran análisis de grafos y algoritmos complejos.

7. **Jupyter Notebook (Dentro de VSCode)**:
    - **Documentación y Reproducibilidad**: Facilita la documentación del flujo de trabajo y la reproducibilidad de los experimentos, permitiendo a otros investigadores seguir y replicar los resultados obtenidos.

8. **Scribbr Citation Generator**:
    - **Generación de Citas y Referencias**: Scribbr Citation Generator es una herramienta en línea que facilita la creación de citas y referencias, en este caso Harvard.

### Tipos de datos básicos empleados en el proyecto

1. lista: Representa una secuencia de nodos o vértices del grafo.

    - Ejemplo: vertices = ['A', 'B', 'C']

2. diccionario: Representa un mapa de adyacencia entre los nodos del grafo.


    - Ejemplo: grafo = {'A': ['B', 'C'], 'B': ['A', 'D'], 'C': ['A', 'F'], 'D': ['B'], 'E': ['F'], 'F': ['C', 'E']}

3. set: Representa un conjunto de nodos o vértices del grafo.


    - Ejemplo: vertices = {'A', 'B', 'C'}

4. tupla: Similar a la lista, pero inmutable.


    - Ejemplo: vertices = ('A', 'B', 'C')

5. numpy.ndarray: Representa una matriz de adyacencia entre los nodos del grafo. Tienen la misma función que los arrays normales pero son más veloces y facilitan los calculos con diversas funciones.


    - Ejemplo: grafo = np.array([[0, 1, 0], [1, 0, 1], [0, 1, 0]])

    
6. scipy.sparse.csr_matrix: Representa una matriz dispersa en formato CSR (Compressed Sparse Row), que es eficiente para operaciones aritméticas y de almacenamiento.

    - Ejemplo: matriz_adyacencia = csr_matrix([[0, 1, 0], [1, 0, 1], [0, 1, 0]])

7. int: Representa un número entero.

    - Ejemplo: num_nodos = 14




#### Creación de una Matriz de adyacencia y representación gráfica del grafo

Se utlizará para medir la velocidad de distintos algoritmos

In [1]:
# Importar librerias
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
import random
from scipy.sparse import csr_matrix

In [2]:
# Crea una gráfica vacía
G = nx.Graph()

# Agrega 20 nodos a la gráfica
for i in range(14):
    G.add_node(i)

# Añade aristas a la gráfica
G.add_edge(0, 3)
G.add_edge(3, 6)
G.add_edge(6, 9)
G.add_edge(9, 10)
G.add_edge(0, 2)
G.add_edge(2, 5)
G.add_edge(5, 8)
G.add_edge(8, 10)
G.add_edge(0, 1)
G.add_edge(1, 4)
G.add_edge(4, 7)
G.add_edge(7, 10)
G.add_edge(3, 6)
G.add_edge(6, 9)
G.add_edge(9, 13)
G.add_edge(13, 10)
G.add_edge(12, 9)
G.add_edge(12, 11)
G.add_edge(11, 10)

# Calcula la matriz de adyacencia actualizada
matriz_adyacencia = nx.to_numpy_array(G)

# Asigna pesos a las aristas de forma sesgada
matriz_adyacencia[matriz_adyacencia == 1] = np.random.randint(1, 5, size=np.count_nonzero(matriz_adyacencia == 1))
matriz_adyacencia[matriz_adyacencia == 0] = np.random.randint(10, 99, size=np.count_nonzero(matriz_adyacencia == 0))
np.fill_diagonal(matriz_adyacencia, 0)
print(matriz_adyacencia)
matriz_adyacencia = csr_matrix(matriz_adyacencia)

[[ 0.  3.  3.  1. 35. 28. 13. 10. 51. 95. 51. 66. 58. 59.]
 [ 2.  0. 23. 19.  3. 86. 95. 55. 19. 70. 79. 36. 33. 28.]
 [ 2. 74.  0. 69. 76.  1. 30. 38. 65. 85. 25. 77. 42. 22.]
 [ 3. 64. 74.  0. 18. 70.  1. 44. 12. 61. 29. 17. 74. 68.]
 [10.  3. 55. 96.  0. 47. 50.  2. 24. 20. 40. 57. 74. 76.]
 [32. 93.  1. 94. 25.  0. 56. 39.  1. 61. 34. 25. 60. 13.]
 [24. 47. 66.  4. 30. 12.  0. 63. 44.  1. 85. 13. 51. 51.]
 [14. 58. 48. 26.  1. 57. 47.  0. 62. 85.  1. 63. 64. 57.]
 [31. 23. 88. 67. 68.  4. 29. 61.  0. 91.  3. 10. 97. 91.]
 [85. 46. 64. 30. 70. 62.  2. 31. 55.  0.  4. 97.  3.  4.]
 [48. 91. 76. 95. 54. 35. 53.  1.  1.  3.  0.  4. 98.  4.]
 [30. 51. 62. 65. 38. 79. 83. 66. 78. 67.  2.  0.  1. 66.]
 [29. 29. 62. 36. 75. 35. 89. 89. 73.  1. 54.  1.  0. 78.]
 [43. 18. 70. 85. 65. 52. 21. 68. 34.  1.  3. 61. 75.  0.]]


In [3]:
# Crear un grafo desde la matriz de adyacencia
G = nx.from_numpy_array(matriz_adyacencia.toarray())

# Dibujar el grafo con nodos en forma de elipse
plt.figure(figsize=(11, 6))

# Número de nodos
num_nodos = len(G.nodes)

# Calcular las posiciones en forma de elipse
pos = {}
for i in range(num_nodos):
    angle = 2 * np.pi * i / num_nodos
    x = np.cos(angle)  
    y = np.sin(angle)
    pos[i] = (x, y)

# Dibujar nodos y aristas
nx.draw(G, pos, with_labels=True, node_color='lightblue', edge_color='gray', node_size=1500, font_size=20)

# Obtener los pesos de las aristas
edge_labels = nx.get_edge_attributes(G, 'weight')

# Dibujar los pesos de las aristas
nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels, font_color='darkblue', font_size=7)

plt.title("Visualización del Grafo con Nodos y Pesos de Aristas")
plt.show()

### Algoritmos de ruta más corta

#### Dijkstra

##### Características:
1. **Aplicabilidad**: Funciona en grafos dirigidos y no dirigidos.
2. **Pesos Positivos**: Solo funciona con grafos que tienen pesos no negativos en las aristas.
3. **Monticulos de Fibonacci**:Utilizo esta versión del Algoritmo porque reduce la complejidad total del algoritmo de Dijkstra de $O((V + E) log V)$ a $O(E + V log V)$, donde $V$ es el número de vértices y $E$ es el número de aristas. Esta mejora es especialmente significativa en grafos densos, donde el número de aristas es mucho mayor que el número de vértices.
4. **Distancias Mínimas**: Calcula las distancias mínimas desde un nodo origen a todos los demás nodos.
5. **No Detección de Ciclos Negativos**: No puede manejar grafos con pesos negativos en las aristas.

##### Pasos:

1. **Inicialización**:
    - Establece la distancia al nodo origen como 0 y a todos los demás nodos como infinito.
    - Marca todos los nodos como no visitados. Establece el nodo origen como el nodo actual.

2. **Selección del Nodo Actual**:
    - Selecciona el nodo no visitado con la distancia más pequeña como el nodo actual.
            
    <img src="./imagenes/Step1Dij.png" alt="Dijkstra 1" width="300"/>     

    Fuente: [Datacamp](https://www.datacamp.com/tutorial/dijkstra-algorithm-in-python)

3. **Actualización de Distancias**:
    - Para el nodo actual, considera todos sus vecinos no visitados y calcula sus distancias tentativas.
    - Compara la distancia recién calculada con la distancia actual asignada y asigna el menor valor.  
          
    <img src="./imagenes/Step2Dij.png" alt="Dijkstra 2" width="300"/>    

    Fuente: [Datacamp](https://www.datacamp.com/tutorial/dijkstra-algorithm-in-python)
4. **Marcar Nodo como Visitado**:
    - Una vez considerados todos los vecinos del nodo actual, marca el nodo actual como visitado. Un nodo visitado no será revisado nuevamente.  
         
    <img src="./imagenes/Step3Dij.png" alt="Dijkstra 3" width="300"/>    
     
    Fuente: [Datacamp](https://www.datacamp.com/tutorial/dijkstra-algorithm-in-python)
5. **Repetición**:
    - Si el nodo destino ha sido marcado como visitado o si la distancia más pequeña entre los nodos no visitados es infinita, el algoritmo termina.
    - De lo contrario, selecciona el nodo no visitado con la distancia más pequeña, establece este nodo como el nuevo nodo actual y repite el proceso.        
    ![Dijkstra Animation](./imagenes/Dijkstra_Animation.gif)      
    Fuente: [Wikipedia](https://es.wikipedia.org/wiki/Algoritmo_de_Dijkstra)
  
**Referencias:**

- M, G.P. (2023) Explicación de algoritmos y estructuras de datos de grafos con Ejemplos en Java y C++. https://www.freecodecamp.org/espanol/news/explicacion-de-algoritmos-y-estructuras-de-datos-de-grafos-con-ejemplos-en-java-y-c/.

- colaboradores de Wikipedia (2024) Algoritmo de Dijkstra. https://es.wikipedia.org/wiki/Algoritmo_de_Dijkstra.

- dijkstra — SciPy v1.14.1 Manual (no date). https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csgraph.dijkstra.html#scipy.sparse.csgraph.dijkstra.

- Tuychiev, B. (2024) Implementing the Dijkstra Algorithm in Python: A Step-by-Step Tutorial. https://www.datacamp.com/tutorial/dijkstra-algorithm-in-python.


In [4]:
#%%timeit
from scipy.sparse.csgraph import dijkstra
# Utiliza el algoritmo de Dijkstra a través de scipy
dist_matrix = dijkstra(matriz_adyacencia, directed=False, indices=0)

print("La distancia mínima entre el nodo 0 y el nodo 13 es:", dist_matrix[13])
print('-------------------------------------------------')
print('Tiempo medio de ejecución: 363 microsegundos')

La distancia mínima entre el nodo 0 y el nodo 13 es: 4.0
-------------------------------------------------
Tiempo medio de ejecución: 363 microsegundos


#### Bellman Ford

##### Características:

1. **Aplicabilidad**: El algoritmo Bellman-Ford se aplica a grafos dirigidos con pesos negativos, ya que no puede manejar aristas con pesos negativos en grafos no dirigidos.
2. **Pesos Negativos**: Puede manejar grafos con pesos negativos en las aristas.
3. **Complejidad Temporal**: Tiene una complejidad temporal de $O(V \cdot E)$, donde $V$ es el número de vértices y $E$ es el número de aristas (este es un límite asintótico que se refiere al peor caso).
4. **Detección de Ciclos Negativos**: Puede detectar la presencia potencial de ciclos de peso negativo en el grafo.
5. **Distancias Mínimas**: Calcula las distancias mínimas desde un nodo origen a todos los demás nodos, siempre y cuando no haya ciclos de peso negativo.

#### Pasos:

**1: Inicialización**

* Se selecciona un nodo origen en el grafo.
* Se establece la distancia al nodo origen como $0$, y se establecen las distancias a todos los demás nodos como infinito (representado por un valor muy grande).

**2: Relajación de aristas**

* El algoritmo repite el siguiente proceso $V-1$ veces, donde $V$ es el número de vértices en el grafo.
* Para cada vértice $v$:
	+ Se revisan todas las aristas incidentes en $v$, es decir, aquellas que comienzan o terminan en $v$.
	+ Para cada arista $(u,v)$ con peso $w$:
		- Si la distancia actual a $u$ más el peso de la arista $w$ es menor que la distancia actual a $v$, se actualiza la distancia a $v$.

**3: Detección de ciclos negativos**

* Después de $V-1$ iteraciones de relaxación de aristas, se revisan todas las aristas una vez más.
* Para cada arista $(u,v)$ con peso $w$:
	+ Si la distancia actual a u más el peso de la arista w es menor que la distancia actual a $v$, significa que hay un ciclo negativo en el grafo.
	+ En este caso, el algoritmo indica la presencia de un ciclo negativo y no puede garantizar la corrección de las distancias mínimas.

**4: Resultado**

* Si no se detecta ningún ciclo negativo después de $V-1$ iteraciones de relaxación de aristas más una última revisión, el algoritmo ha encontrado las distancias mínimas desde el nodo origen a todos los demás nodos en el grafo.
* Las distancias mínimas están almacenadas en la matriz de distancias, que es una tabla que contiene la distancia mínima desde el nodo origen a cada vértice en el grafo.


**Referencias:**
- Jariasf (2013) CAMINO MAS CORTO: ALGORITMO DE BELLMAN-FORD. https://jariasf.wordpress.com/2013/01/01/camino-mas-corto-algoritmo-de-bellman-ford/.

- M, G.P. (2023) Explicación de algoritmos y estructuras de datos de grafos con Ejemplos en Java y C++. https://www.freecodecamp.org/espanol/news/explicacion-de-algoritmos-y-estructuras-de-datos-de-grafos-con-ejemplos-en-java-y-c/.

- bellman_ford — SciPy v1.14.1 Manual (no date). https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csgraph.bellman_ford.html#scipy.sparse.csgraph.bellman_ford.


In [5]:
#%%timeit
from scipy.sparse.csgraph import bellman_ford

# Utiliza el algoritmo de Bellman-Ford a través de scipy
dist_matrix = bellman_ford(matriz_adyacencia, directed=False, indices=0, return_predecessors=False)

print("La distancia mínima entre el nodo 0 y el nodo 13 es:", dist_matrix[13])
print('-------------------------------------------------')
print('Tiempo de ejecución: 163 microsegundos')

La distancia mínima entre el nodo 0 y el nodo 13 es: 4.0
-------------------------------------------------
Tiempo de ejecución: 163 microsegundos


#### Johnson

##### Características:

1. **Aplicabilidad**: El algoritmo de Johnson se aplica a grafos dirigidos y no dirigidos.
2. **Pesos Positivos y Negativos**: Puede manejar grafos con pesos positivos y negativos en las aristas, siempre y cuando no existan ciclos de peso negativo.
3. **Complejidad Temporal**: Tiene una complejidad temporal de $O(V^2 \log V + VE)$, donde $V$ es el número de vértices y $E$ es el número de aristas.
4. **Distancias Mínimas**: Calcula las distancias mínimas entre todos los pares de nodos en el grafo.
5. **Uso de Algoritmos Auxiliares**: Utiliza el algoritmo de Bellman-Ford para reponderar los pesos de las aristas y luego aplica el algoritmo de Dijkstra para encontrar las distancias más cortas.

##### Pasos:

1. **Añadir nuevo nodo**
	Primero se añade un nuevo nodo q al grafo, conectado a cada uno de los nodos del grafo por una arista de peso cero.

2. **Ejecutar Bellman-Ford**
	En segundo lugar, se utiliza el algoritmo de Bellman-Ford, empezando por el nuevo vértice q, para determinar para cada vértice v el peso mínimo $h(v)$ del camino de q a v. Si en este paso se detecta un ciclo negativo, el algoritmo concluye.

3. **Modificar pesos**
	Seguidamente, a las aristas del grafo original se les cambia el peso usando los valores calculados por el algoritmo de Bellman-Ford: una arista de u a v con tamaño $w(u, v)$, da el nuevo tamaño $w(u, v) + h(u) - h(v)$.

4. **Ejecutar Dijkstra**
	Por último, para cada nodo s se usa el algoritmo de Dijkstra (tambien con monticulos de Fibonacci) para determinar el camino más corto entre s y los otros nodos, usando el grafo con pesos modificados.    
       
![Johnson Algorithm](./imagenes/AlgJohnsonImg.png)   
Fuente: [Wikipedia](https://es.wikipedia.org/wiki/Algoritmo_de_Johnson)   
 
**Referencias:**

- colaboradores de Wikipedia (2020) Algoritmo de Johnson. https://es.wikipedia.org/wiki/Algoritmo_de_Johnson.
- johnson — SciPy v1.14.1 Manual (no date). https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csgraph.johnson.html#scipy.sparse.csgraph.johnson.

In [6]:
#%%timeit
from scipy.sparse.csgraph import johnson

#Utiliza el algoritmo de Johnson a través de scipy
dist_matrix = johnson(matriz_adyacencia, directed=False, indices=0)
print("La distancia mínima entre el nodo 0 y el nodo 13 es:", dist_matrix[13])
print('-------------------------------------------------')
print('Tiempo de ejecución: 435 microsegundos')

La distancia mínima entre el nodo 0 y el nodo 13 es: 4.0
-------------------------------------------------
Tiempo de ejecución: 435 microsegundos


#### Floyd-Warshall

##### Características:

1. **Aplicabilidad**: El algoritmo de Floyd-Warshall se aplica a grafos dirigidos y no dirigidos.
2. **Pesos Positivos y Negativos**: Puede manejar grafos con pesos positivos y negativos en las aristas, siempre y cuando no existan ciclos de peso negativo.
3. **Complejidad Temporal**: Tiene una complejidad temporal de $O(V^3)$, donde $V$ es el número de vértices.
4. **Distancias Mínimas**: Calcula las distancias mínimas entre todos los pares de nodos en el grafo.
5. **Simplicidad**: Es un algoritmo sencillo de implementar y entender.

##### Pasos:

1. **Inicialización**
    - Crear una matriz de distancias `dist` donde `dist[i][j]` es la distancia entre el nodo `i` y el nodo `j`. Inicialmente, `dist[i][j]` es el peso de la arista entre `i` y `j` si existe, de lo contrario es infinito. La distancia de un nodo a sí mismo es 0.

2. **Iteración**
    - Para cada nodo `k`, actualizar la matriz de distancias considerando `k` como un nodo intermedio. Para cada par de nodos `(i, j)`, actualizar `dist[i][j]` como el mínimo entre `dist[i][j]` y `dist[i][k] + dist[k][j]`.

3. **Resultado**
    - Después de completar las iteraciones, la matriz `dist` contendrá las distancias mínimas entre todos los pares de nodos.

<img src = './imagenes/Floyd-Warshall-Algorithm-Problem.png' width=700></img>

Fuente: [Wikipedia](https://es.wikipedia.org/wiki/Algoritmo_de_Floyd-Warshall)

**Referencias:**

- colaboradores de Wikipedia (2020) Algoritmo de Floyd-Warshall. https://es.wikipedia.org/wiki/Algoritmo_de_Floyd-Warshall.
- floyd_warshall — SciPy v1.14.1 Manual (no date). https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csgraph.floyd_warshall.html#scipy.sparse.csgraph.floyd_warshall.

In [7]:
#%%timeit
from scipy.sparse.csgraph import floyd_warshall

#Utiliza el algoritmo de Johnson a través de scipy
dist_matrix = floyd_warshall(matriz_adyacencia, directed=False)

#Nota: Este algoritmo no permite calcular la distancia eligiendo un nodo de inicio
print("La distancia mínima entre el nodo 0 y el nodo 13 es:", dist_matrix[0,13])
print('-------------------------------------------------')
print('Tiempo de ejecución: 85 microsegundos')

La distancia mínima entre el nodo 0 y el nodo 13 es: 4.0
-------------------------------------------------
Tiempo de ejecución: 85 microsegundos


### Elección final de Algoritmo de camino más corto

Pues no he elegido ninguno, en su lugar una función de scipy, La función `scipy.sparse.csgraph.shortest_path` elige automáticamente el mejor algoritmo para encontrar las rutas más cortas dependiendo de las características del grafo de entrada.

Opciones del parametro `method` y un breve resumen de los algoritmos ya vistos previamente:

`auto` – (por defecto) selecciona la mejor opción entre ‘FW’, ‘D’, ‘BF’ o ‘J’
basado en los datos de entrada.

`FW` – Algoritmo de Floyd-Warshall.
El costo computacional es aproximadamente $O[N^3]$. 

`D` – Algoritmo de Dijkstra con pilas de Fibonacci.
El costo computacional es aproximadamente $O[N(N*k + N\log(N))]$, donde $k$ es el número promedio de aristas conectadas por nodo. 

`BF` – Algoritmo de Bellman-Ford.
Este algoritmo puede usarse cuando los pesos son negativos. Si se encuentra un ciclo negativo, se levantará una excepción. El costo computacional es aproximadamente $O[N(N^2 k)]$, donde $k$ es el número promedio de aristas conectadas por nodo.

`J` – Algoritmo de Johnson.
Al igual que el algoritmo de Bellman-Ford, el algoritmo de Johnson está diseñado para usarse cuando los pesos son negativos. Combina el algoritmo de Bellman-Ford con el algoritmo de Dijkstra para una computación más rápida.




**Referencias**
- shortest_path — SciPy v1.14.1 Manual (no date). https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csgraph.shortest_path.html#scipy.sparse.csgraph.shortest_path.

In [8]:
#%%timeit
from scipy.sparse.csgraph import shortest_path

# Utiliza la función shortest_path para encontrar la ruta más rápida desde el nodo 0 al 13
dist_matrix= shortest_path(matriz_adyacencia, method='auto' ,directed=False, indices=0, return_predecessors=False)

print("La distancia mínima entre el nodo 0 y el nodo 13 es:", dist_matrix[13])
print('-------------------------------------------------')
print('Tiempo de ejecución: 228 microsegundos')

La distancia mínima entre el nodo 0 y el nodo 13 es: 4.0
-------------------------------------------------
Tiempo de ejecución: 228 microsegundos
